# dist: xenial
# group: edge
language: cpp
compiler:
- clang
- gcc
env:
  global:
  matrix:
  # - GLIB=glib-2.40.2  GLIB_VERSION=2.40 # OK
  # - GLIB=glib-2.41.5  GLIB_VERSION=2.41
  # - GLIB=glib-2.44.1  GLIB_VERSION=2.44
  # - GLIB=glib-2.46.2  GLIB_VERSION=2.46
  # - GLIB=glib-2.47.92 GLIB_VERSION=2.47
  # - GLIB=glib-2.48.2  GLIB_VERSION=2.48
  - GLIB=glib-2.49.7  GLIB_VERSION=2.49  
  - GLIB=glib-2.50.3  GLIB_VERSION=2.50
  - GLIB=glib-2.55.0  GLIB_VERSION=2.55
matrix:
#   include:
#   - os: linux
#     addons:
#       apt:
#         sources:
#         - llvm-toolchain-trusty-5.0
#         packages:
#         - clang-5.0 # It is now the default one no more need to update!
#   - os: linux
#     addons:
#       apt:
#         sources:
#         - ubuntu-toolchain-r-test
#         packages:
#         - gcc-7
#     env:
#     - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"
  allow_failures:
  - env: GLIB=glib-2.54.2 GLIB_VERSION=2.54
  #^ libmount-dev (2.20.1-5.1ubuntu20.9) from Ubuntu 14.04 probably too old.
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test # TODO better put it in the matrix!
    # - llvm-toolchain-trusty-5.0 # TODO better put it in the matrix!
    # - debian-sid # This is ok for packages with little dependencies like libmount-dev, but not for clang!
    packages:
    # as requested by configure
    - libmount-dev
    # - gcc-4.9
    # - gcc-7 # TODO better put it in the matrix!
    # - clang-5.0 # TODO better put it in the matrix!
before_install:
- apt-cache policy libglib2.0-dev libmount-dev libelf-dev
install:
- wget http://ftp.gnome.org/pub/gnome/sources/glib/$GLIB_VERSION/$GLIB.tar.xz # 2.1s
# - wget https://git.gnome.org/browse/glib/snapshot/$GLIB.tar.xz # 35s
- tar --xz --extract --file=$GLIB.tar.xz
- ls --color
- cd $GLIB
- ls --color
- cat INSTALL
- ./configure --help
- ./configure --prefix=/tmp/local

- mount
- mount | grep tmpfs
- ls -l --color /run
# In sudo mode tmpfs size could be inceased and compilation could be made there.

- pip install --user psutil
- JOBS="$(python -c 'import psutil ; print len(psutil.Process().cpu_affinity())')" # 2 jobs at a time in make

script:
- apt-cache policy make
- make --version # Waiting for version 4.0 to be able to use --output-sync=recurse
# https://www.gnu.org/software/make/manual/html_node/Parallel-Output.html
- make --jobs=$JOBS && make install --jobs=$JOBS
- make --jobs=$JOBS test || true
- echo $JOBS
