language: c
compiler:
# - clang
- gcc
env:
  global:
  matrix:
  - GLIB=glib-2.40.2 GLIB_VERSION=2.40
  # - GLIB=glib-2.54.2
addons:
  apt:
    sources:
    # - ubuntu-toolchain-r-test
    packages:
    # as requested by configure
    - libmount-dev
    # - gcc-4.9
before_install:
- apt-cache policy libglib2.0-dev libmount-dev libelf-dev
install:
- wget http://ftp.gnome.org/pub/gnome/sources/glib/$GLIB_VERSION/$GLIB.tar.xz # 2.1s
# - wget https://git.gnome.org/browse/glib/snapshot/$GLIB.tar.xz # 35s
- tar --xz --extract --file=$GLIB.tar.xz
- ls --color
- cd $GLIB
- ls --color
- cat INSTALL
- ./configure --help
- ./configure --prefix=/tmp/local

script:
- make && make install
- make test || true
