# dist: xenial
# group: edge
language: c
compiler:
- clang
# - gcc # finding libmount compatible version...
env:
  global:
  matrix:
  # - GLIB=glib-2.40.2  GLIB_VERSION=2.40 # OK
  # - GLIB=glib-2.41.5  GLIB_VERSION=2.41
  # - GLIB=glib-2.44.1  GLIB_VERSION=2.44
  # - GLIB=glib-2.46.2  GLIB_VERSION=2.46
  # - GLIB=glib-2.47.92 GLIB_VERSION=2.47
  # - GLIB=glib-2.48.2  GLIB_VERSION=2.48
  - GLIB=glib-2.49.7  GLIB_VERSION=2.49  
  - GLIB=glib-2.50.3  GLIB_VERSION=2.50
  - GLIB=glib-2.55.0  GLIB_VERSION=2.55
matrix:
  allow_failures:
  - env: GLIB=glib-2.54.2 GLIB_VERSION=2.54
  #^ libmount-dev (2.20.1-5.1ubuntu20.9) from Ubuntu 14.04 probably too old.
addons:
  apt:
    sources:
    # - ubuntu-toolchain-r-test
    # - llvm-toolchain-trusty-5.0
    - debian-sid
    packages:
    # as requested by configure
    - libmount-dev
    # - gcc-4.9
    # - gcc-7
    # - clang-5.0
before_install:
- apt-cache policy libglib2.0-dev libmount-dev libelf-dev
install:
- wget http://ftp.gnome.org/pub/gnome/sources/glib/$GLIB_VERSION/$GLIB.tar.xz # 2.1s
# - wget https://git.gnome.org/browse/glib/snapshot/$GLIB.tar.xz # 35s
- tar --xz --extract --file=$GLIB.tar.xz
- ls --color
- cd $GLIB
- ls --color
- cat INSTALL
- ./configure --help
- ./configure --prefix=/tmp/local

script:
- make && make install
- make test || true
